require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/stand_users", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # StandUser. As you add validations to StandUser, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # StandUsersController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      StandUser.create! valid_attributes
      get stand_users_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      stand_user = StandUser.create! valid_attributes
      get stand_user_url(stand_user), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new StandUser" do
        expect {
          post stand_users_url,
               params: { stand_user: valid_attributes }, headers: valid_headers, as: :json
        }.to change(StandUser, :count).by(1)
      end

      it "renders a JSON response with the new stand_user" do
        post stand_users_url,
             params: { stand_user: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new StandUser" do
        expect {
          post stand_users_url,
               params: { stand_user: invalid_attributes }, as: :json
        }.to change(StandUser, :count).by(0)
      end

      it "renders a JSON response with errors for the new stand_user" do
        post stand_users_url,
             params: { stand_user: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested stand_user" do
        stand_user = StandUser.create! valid_attributes
        patch stand_user_url(stand_user),
              params: { stand_user: new_attributes }, headers: valid_headers, as: :json
        stand_user.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the stand_user" do
        stand_user = StandUser.create! valid_attributes
        patch stand_user_url(stand_user),
              params: { stand_user: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the stand_user" do
        stand_user = StandUser.create! valid_attributes
        patch stand_user_url(stand_user),
              params: { stand_user: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested stand_user" do
      stand_user = StandUser.create! valid_attributes
      expect {
        delete stand_user_url(stand_user), headers: valid_headers, as: :json
      }.to change(StandUser, :count).by(-1)
    end
  end
end
